$kind: http-request
method: GET
url: '{{base_url}}/api/task-lists/{{task_list_id}}/tasks/{{task_id}}'
order: 15000
scripts:
  - type: afterResponse
    language: text/javascript
    code: |-
      pm.test("status is 404", () => pm.response.to.have.status(404));
      pm.test("reports not found", () =>
        pm.expect(pm.response.json().message).to.eql("Task not found"));
