$kind: http-request
method: PUT
url: '{{base_url}}/task_list/{{task_list_id}}/tasks/{{task_id}}'
order: 11000
headers:
  - key: Content-Type
    value: application/json
body:
  type: json
  content: |-
    {
      "id": "{{task_id}}",
      "title": "x",
      "priority": "LOW"
    }
scripts:
  - type: afterResponse
    language: text/javascript
    code: |-
      pm.test("status is 400", () => pm.response.to.have.status(400));
      pm.test("requires a status", () =>
        pm.expect(pm.response.json().message).to.eql("Task  must have a status!"));
